feature:
  - changed-files:
    - any-glob-to-any-file: ['src/**/*']

bugfix:
  - changed-files:
    - any-glob-to-any-file: ['src/**/*']

documentation:
  - changed-files:
    - any-glob-to-any-file: ['*.md', 'docs/**/*']

dependencies:
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'package-lock.json']

testing:
  - changed-files:
    - any-glob-to-any-file: ['**/*.test.*', '**/*.spec.*', 'src/test/**/*']

ci:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']

refactor:
  - changed-files:
    - any-glob-to-any-file: ['src/**/*']

enhancement:
  - changed-files:
    - any-glob-to-any-file: ['src/**/*']